### ISSUE TITLE
[Open-source] Looking forward to open-sourced data and codebase~

### ISSUE THREAD

**Issue by Li-Qingyun** [wangzhecheng/SkyScript#1]
Hi, thanks for your great work of SkyScript, which makes great progress for RS community. We are looking forward to the open-sourced data and codebase ASAP. What is the schedule of the data releasing.

**Comment by wangzhecheng** [comment]
Hi Qingyun, we will make them online by the end of this weekend. Thanks!

**Comment by Li-Qingyun** [comment]
Great! Thanks!
